"""Generates paper/tables/h2_depth_heterogeneity.tex from the machine-
readable depth-heterogeneity outputs. No number in this table is
hand-transcribed. Explicitly post-run/exploratory -- not part of the
confirmatory Table (tab:confirmatory-summary), which is left unchanged.
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
DEPTH_DIR = REPO_ROOT / "results" / "h2_robustness" / "depth_heterogeneity"
REPL_DIR = REPO_ROOT / "results" / "h2_replication_v1" / "depth_heterogeneity"
OUT_PATH = REPO_ROOT / "paper" / "tables" / "h2_depth_heterogeneity.tex"


def fmt(x, nd=4):
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return "--"
    return f"{x:.{nd}f}"


def fmt_ci(lo, hi, nd=4):
    return f"[{fmt(lo, nd)}, {fmt(hi, nd)}]"


def main() -> None:
    orig_cont = pd.read_csv(DEPTH_DIR / "original_continuous_model.csv")
    repl_cont = pd.read_csv(REPL_DIR / "replication_continuous_model.csv")
    orig_omni = pd.read_csv(DEPTH_DIR / "original_omnibus_tests.csv").iloc[0]
    repl_omni = pd.read_csv(REPL_DIR / "replication_omnibus_tests.csv").iloc[0]
    diagnostics = json.loads((DEPTH_DIR / "model_diagnostics.json").read_text())
    orig_cr_omni = diagnostics["original"]["cluster_robust_omnibus"]
    repl_cr_omni = diagnostics["replication"]["cluster_robust_omnibus"]
    orig_depth = pd.read_csv(DEPTH_DIR / "original_depth_contrasts.csv").set_index("depth")
    repl_depth = pd.read_csv(REPL_DIR / "replication_depth_contrasts.csv").set_index("depth")
    orig_w = pd.read_csv(DEPTH_DIR / "original_weighted_contrasts.csv").set_index("weighting")
    repl_w = pd.read_csv(REPL_DIR / "replication_weighted_contrasts.csv").set_index("weighting")
    summary_json = json.loads((DEPTH_DIR / "h2_depth_heterogeneity_summary.json").read_text())
    classification = summary_json["depth_pattern_classification"]

    orig_el_depthz = orig_cont[orig_cont["coefficient"] == "E:L:depth_z"].iloc[0]
    repl_el_depthz = repl_cont[repl_cont["coefficient"] == "E:L:depth_z"].iloc[0]

    lines = []
    lines.append(r"\begin{table*}[t]")
    lines.append(r"\centering")
    lines.append(r"\footnotesize")
    lines.append(r"\caption{\textbf{Post-run, exploratory H2 depth-heterogeneity analysis.} "
                 r"Not part of the confirmatory family (Table~\ref{tab:confirmatory-summary}); "
                 r"no Holm or other multiplicity correction is applied to any value below, and "
                 r"none of it changes the prespecified Wald/Holm rejection of H2. Original and "
                 r"replication fits are separate (never pooled); intervals are 95\% Wald unless "
                 r"noted. Generated by \ttf{paper/scripts/make\_table\_h2\_depth\_heterogeneity.py} "
                 r"from \ttf{results/h2\_robustness/depth\_heterogeneity/} and "
                 r"\ttf{results/h2\_replication\_v1/depth\_heterogeneity/}.}")
    lines.append(r"\label{tab:h2-depth-heterogeneity}")
    lines.append(r"\begin{tabularx}{\textwidth}{@{}l>{\raggedright\arraybackslash}X l l@{}}")
    lines.append(r"\toprule")
    lines.append(r"Check & Quantity & Original & Replication \\")
    lines.append(r"\midrule")
    lines.append(rf"Continuous moderation & $E{{:}}L{{:}}\mathrm{{depth}}_z$ coefficient (95\% CI) & "
                 rf"{fmt(orig_el_depthz['estimate'])} {fmt_ci(orig_el_depthz['ci95_lo'], orig_el_depthz['ci95_hi'])} & "
                 rf"{fmt(repl_el_depthz['estimate'])} {fmt_ci(repl_el_depthz['ci95_lo'], repl_el_depthz['ci95_hi'])} \\")
    lines.append(rf"Categorical omnibus (mixed model) & Joint Wald $\chi^2$ (df={int(orig_omni['df_numerator'])}), $p$ & "
                 rf"$\chi^2={orig_omni['statistic']:.2f}$, $p={orig_omni['p_unadjusted']:.2e}$ & "
                 rf"$\chi^2={repl_omni['statistic']:.2f}$, $p={repl_omni['p_unadjusted']:.2e}$ \\")
    lines.append(rf"Categorical omnibus (cluster-robust) & Joint Wald $\chi^2$ (df=4), $p$ & "
                 rf"$\chi^2={orig_cr_omni['statistic']:.2f}$, $p={orig_cr_omni['p_unadjusted']:.2f}$ & "
                 rf"$\chi^2={repl_cr_omni['statistic']:.2f}$, $p={repl_cr_omni['p_unadjusted']:.2f}$ \\")
    lines.append(r"\midrule")
    lines.append(r"\multicolumn{4}{@{}l}{\textit{Depth-specific $E{:}L$ contrast (categorical mixed model, 95\% CI)}} \\")
    for d in (1, 2, 3, 4, 6):
        o, r = orig_depth.loc[d], repl_depth.loc[d]
        lines.append(rf"$D={d}$ & -- & {fmt(o['estimate'])} {fmt_ci(o['ci95_lo'], o['ci95_hi'])} & "
                     rf"{fmt(r['estimate'])} {fmt_ci(r['ci95_lo'], r['ci95_hi'])} \\")
    lines.append(r"\midrule")
    eo, ro = orig_w.loc["equal_depth"], repl_w.loc["equal_depth"]
    oo, roo = orig_w.loc["observation_count"], repl_w.loc["observation_count"]
    lines.append(rf"Equal-depth weighted & $\sum_d \tfrac{{1}}{{5}} \cdot$ contrast$(d)$ & "
                 rf"{fmt(eo['estimate'])} {fmt_ci(eo['ci95_lo'], eo['ci95_hi'])} & "
                 rf"{fmt(ro['estimate'])} {fmt_ci(ro['ci95_lo'], ro['ci95_hi'])} \\")
    lines.append(rf"Observation-weighted & $\sum_d (n_d/n) \cdot$ contrast$(d)$ & "
                 rf"{fmt(oo['estimate'])} {fmt_ci(oo['ci95_lo'], oo['ci95_hi'])} & "
                 rf"{fmt(roo['estimate'])} {fmt_ci(roo['ci95_lo'], roo['ci95_hi'])} \\")
    adopted = orig_w.loc["adopted_confirmatory_pooled"]
    repl_pooled = repl_w.loc["replication_pooled_wald"]
    lines.append(rf"Adopted / pooled Wald & Full-pooling confirmatory model & "
                 rf"{fmt(adopted['estimate'])} {fmt_ci(adopted['ci95_lo'], adopted['ci95_hi'])} & "
                 rf"{fmt(repl_pooled['estimate'])} {fmt_ci(repl_pooled['ci95_lo'], repl_pooled['ci95_hi'])} \\")
    lines.append(r"\midrule")
    lines.append(rf"\multicolumn{{4}}{{@{{}}l}}{{Original-vs-replication depth pattern: \textit{{{classification}}}}} \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabularx}")
    lines.append(r"\end{table*}")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
