"""Add descriptive gradient/task and cross-seed comparisons to task metrics."""
import json
from pathlib import Path
import numpy as np,pandas as pd
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'results/task_metrics/prepared_state';PLAN='645521db6511ca049d89e64f810e65a3407a7b52';ANALYSIS='9327aca680713423c5820db76b22ed1fb471a3d2'
inputs={'original':ROOT/'results/production_confirmatory/raw/exact.parquet','independent_seed':ROOT/'results/h2_replication_v1/_pipeline_output_stage1/raw/exact.parquet'}
summary=pd.read_csv(OUT/'configuration_depth_summary.csv');frames=[]
for label,p in inputs.items():
 d=pd.read_parquet(p);g=d.groupby(['configuration_id','E','L','R','depth']).exact_gradient.apply(lambda x:np.sqrt(np.mean(x**2))).rename('rms_exact_gradient').reset_index();g.insert(0,'dataset',label);frames.append(g)
grad=pd.concat(frames,ignore_index=True);wide=summary.pivot(index=['dataset','configuration_id','E','L','R','depth'],columns='metric',values='mean').reset_index();comparison=wide.merge(grad,validate='one_to_one');comparison.to_csv(OUT/'gradient_metric_comparison.csv',index=False)
obj=pd.read_csv(OUT/'prepared_state_metrics.csv').groupby(['dataset','L']).agg(mean_energy=('normalized_prepared_state_energy','mean'),mean_fidelity=('prepared_state_fidelity','mean'),n=('prepared_state_fidelity','size')).reset_index();obj.to_csv(OUT/'objective_summary.csv',index=False)
o=wide[wide.dataset=='original'].drop(columns='dataset');s=wide[wide.dataset=='independent_seed'].drop(columns='dataset');cross=o.merge(s,on=['configuration_id','E','L','R','depth'],suffixes=('_original','_seed'));cross.to_csv(OUT/'cross_seed_cell_comparison.csv',index=False)
maxfid=float(np.max(np.abs(cross.prepared_state_fidelity_seed-cross.prepared_state_fidelity_original)));maxenergy=float(np.max(np.abs(cross.normalized_prepared_state_energy_seed-cross.normalized_prepared_state_energy_original)))
manifest=json.loads((OUT/'manifest.json').read_text());manifest['analysis_commit']=ANALYSIS;manifest['descriptive_comparison_files']=['gradient_metric_comparison.csv','objective_summary.csv','cross_seed_cell_comparison.csv'];(OUT/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
lines=['# Prepared-state task metrics','',f'**Status:** post-primary descriptive initialization-state metrics; plan `{PLAN}`. No optimization was performed.','', 'Generated 4,000 unique terminal-block prepared states; all bounds/complementarity and predeclared exact-gradient checks passed.','']
for label in inputs:
 z=wide[wide.dataset==label];lines.append(f"- {label}: configuration-depth mean fidelity spans {z.prepared_state_fidelity.min():.4f} to {z.prepared_state_fidelity.max():.4f}; mean normalized energy spans {z.normalized_prepared_state_energy.min():.4f} to {z.normalized_prepared_state_energy.max():.4f}.")
lines+=['',f'Across matched configuration-depth cells, the largest absolute seed-set difference is {maxfid:.4f} in mean fidelity and {maxenergy:.4f} in mean normalized energy. Objective-level means are retained in `objective_summary.csv`; L=0 and L=1 means are exactly identical because objective choice changes the evaluated cost but not the prepared state. The ranges overlap strongly across seed sets, so no conspicuous seed-unstable task-metric separation is evident descriptively.', '', 'The source table `gradient_metric_comparison.csv` places RMS exact-gradient magnitude beside energy and fidelity without a significance test. It does not establish that larger initialization gradients improve task metrics, and no causal or optimization claim is made.', '', 'These are prepared-state-at-initialization descriptions. They do not demonstrate optimization convergence, final performance, trainability, hardware advantage, or savings.']
(ROOT/'verification/task_metrics_results.md').write_text('\n'.join(lines)+'\n',encoding='utf-8');res={'status':'post_primary_descriptive','plan_commit':PLAN,'analysis_commit':ANALYSIS,'rows':4000,'max_cross_seed_mean_fidelity_difference':maxfid,'max_cross_seed_mean_normalized_energy_difference':maxenergy,'paths':{'summary':'results/task_metrics/prepared_state/configuration_depth_summary.csv','gradient_comparison':'results/task_metrics/prepared_state/gradient_metric_comparison.csv','objective':'results/task_metrics/prepared_state/objective_summary.csv'}};(ROOT/'verification/task_metrics_results.json').write_text(json.dumps(res,indent=2)+'\n')
