"""Generate measurement-protocol audit and deterministic resource records."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
import pandas as pd
from qnn_snr.resource_audit import resource_rows,validate_resource_table
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'results/resource_accounting';PLAN='645521db6511ca049d89e64f810e65a3407a7b52'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p,x):p.write_text(json.dumps(x,indent=2,default=float)+'\n',encoding='utf-8')
def main():
 if OUT.exists():raise FileExistsError(OUT)
 OUT.mkdir();table,jobs=resource_rows();prod=pd.read_csv(ROOT/'results/production_confirmatory/resource_accounting.csv');validation=validate_resource_table(table,prod)
 table.to_csv(OUT/'resource_table.csv',index=False);table.to_parquet(OUT/'resource_table.parquet',index=False);jobs.to_parquet(OUT/'job_details.parquet',index=False);dump(OUT/'validation.json',validation)
 pw=pd.read_parquet(ROOT/'results/production_confirmatory/pointwise_gradient_statistics.parquet');z=pw[pw.zero_variance_flag].merge(table,on=['analysis_mode','configuration_id','depth','budget'],how='left',validate='many_to_one',indicator=True)
 if len(z)!=int(pw.zero_variance_flag.sum()) or not (z._merge=='both').all():raise RuntimeError('zero variance join incomplete')
 z.drop(columns='_merge').to_csv(OUT/'zero_variance_resource_join.csv',index=False)
 protocol={'global_target_infidelity':{'implementation':'direct Bernoulli sampling from exact overlap_probability(state,psi_0)','outcomes':'success count k of n; estimator 1-k/n','objective_settings':1,'job_basis_label':'overlap','inverse_state_preparation_circuit':False,'target_gates_represented_or_counted':False,'hardware_equivalence':False},'tfim_energy':{'H':'-J sum Z_i Z_(i+1) - h sum X_i, open boundary','terms':{'ZZ':3,'X':4},'settings':2,'groups':['z','x'],'allocation':'each shifted terminal state receives separate Z and X jobs; shared multinomial within basis','covariance':'within-basis joint sampling implicit; cross-basis covariance absent'},'modes':{'finite_shot_end_to_end':'sample forward Z features, shifted node Jacobians, shifted terminal objective; noisy features nonlinearly re-encoded','finite_shot_conditional':'forward features exact/fixed; shifted node Jacobians and terminal objective sampled; forward-feature variance excluded'},'budget':'B covers the complete gradient-vector job list; floor allocation plus deterministic sorted remainder','omitted':['physical gate count','target inverse-preparation gates','calibration','readout overhead','hardware noise','wall-clock scheduling']};dump(OUT/'measurement_protocol.json',protocol)
 d6=table.query('depth==6');low=d6.query("analysis_mode=='finite_shot_conditional' and L==0").total_jobs.unique().item();high=d6.query("analysis_mode=='finite_shot_end_to_end' and L==1").total_jobs.unique().item();ratio=(high-low)/low
 manifest={'plan_commit':PLAN,'analysis_commit':None,'inputs':{p:sha(ROOT/p) for p in ['qnn_snr/budget.py','qnn_snr/gradients.py','qnn_snr/costs.py','results/production_confirmatory/resource_accounting.csv','results/production_confirmatory/pointwise_gradient_statistics.parquet']},'command':'python scripts/run_resource_accounting.py','d6_extreme_job_counts':{'conditional_global':low,'end_to_end_local':high,'relative_difference':ratio},'zero_variance_join_rows':len(z)};dump(OUT/'manifest.json',manifest)
 report=f'''# Measurement and resource accounting\n\n**Status:** implementation audit/descriptive accounting; plan `{PLAN}`.\n\nThe global target-infidelity estimator does not construct an inverse target-state circuit. It draws a binomial count directly from the exact statevector overlap probability and records one abstract `overlap` objective setting; target-preparation/inverse gates and physical costs are not represented. “One basis” is accurate only as one observable setting in this simulator abstraction.\n\nTFIM energy uses two settings: one Z-basis multinomial jointly estimates three ZZ terms and one X-basis multinomial jointly estimates four X terms. End-to-end additionally samples D-1 forward-feature Z jobs and re-encodes noisy features; conditional mode holds those features exact and excludes their variance. Modes are separate.\n\nAll {len(table)} design rows conserve requested B exactly, have nonnegative deterministic allocations and zero zero-shot production jobs. The zero-variance join contains {len(z)} cells with complete resource matches. At D=6 the manuscript extremes are {low} jobs (conditional/global) versus {high} (end-to-end/local), a {ratio*100:.2f}% increase, reproducing the approximately 27% claim.\n\nOnly total implemented shot budget is matched—not shots per circuit, circuits/jobs, physical gates, calibration, readout, noise, or wall-clock time.\n''';(ROOT/'verification/measurement_resource_accounting.md').write_text(report,encoding='utf-8');dump(ROOT/'verification/measurement_resource_accounting.json',{'status':'implementation_audit','plan_commit':PLAN,'analysis_commit':None,'validation':validation,'d6_job_ratio':ratio,'zero_variance_join_rows':len(z),'protocol':protocol})
if __name__=='__main__':main()
